<?php
/**
 * Created by PhpStorm.
 * User: joaquin
 * Date: 11/03/19
 * Time: 20:59
 */

namespace App\Enums;


class Perfiles
{
    const OPERADOR_VENTA = "OPERADOR VENTA";
    const OPERADOR_AUDITORIA = "OPERADOR AUDITORIA";
    const OPERADOR_LOGISTICA = "OPERADOR LOGISTICA";
    const OPERADOR_VALIDACION = "OPERADOR VALIDACION";
    const SUPERVISOR_CALL = "SUPERVISOR CALL";
    const SUPERVISOR_VENDEDORAS = "SUPERVISOR VENDEDORAS";
    const ADMINISTRADO_VENTAS = "ADMINISTRADOR VENTAS";
    const SUPERVISOR_LOGISTICA = "SUPERVISOR LOGISTICA";
    const ESTADISTICAS = "ESTADISTICAS";
    const VENDEDORA = "VENDEDORA";
    const CADETE = "CADETE";
    const EXTERNO = "EXTERNO";
    const PROMOTORA = "PROMOTORA";
    const TEAM_LEADER = "TEAM LEADER";
}